"""
Data contracts for the Research Agent.

Three categories:
1. ``ResearchAgentState``  — LangGraph TypedDict that flows between nodes.
2. Structured-output models — Pydantic models used with ``.with_structured_output()``.
3. ``ResearchAgentOutput``  — Final result returned by ``ResearchAgent.run()``.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field
from typing_extensions import TypedDict


# ---------------------------------------------------------------------------
# LangGraph state
# ---------------------------------------------------------------------------


class ResearchAgentState(TypedDict):
    """Mutable state object passed between every node in the research graph.

    LangGraph merges node return dicts into this state via reducers.
    Only the fields a node touches need to be returned — unset keys keep their
    previous value.

    Fields
    ------
    query : str
        The original user research question.  Read-only after initialisation.
    session_id : str
        Research session UUID.  Used to scope Qdrant queries.
    iteration : int
        Loop counter from the outer orchestration graph (0-indexed).
    research_plan : list[str]
        Targeted search queries generated by the planner node.
    rag_results : list[dict[str, Any]]
        Raw results from Qdrant — each dict is a serialised ``RetrievalResult``.
    web_results : list[dict[str, Any]]
        Raw results from Tavily — each dict is a serialised ``WebSearchResult``.
    findings : list[Finding]
        Structured, cited findings produced by the synthesizer node.
    status : str
        Current execution phase; set to ``"failed"`` to short-circuit to END.
    error : str | None
        Error message set when ``status == "failed"``.
    """

    query: str
    session_id: str
    mode: str
    iteration: int
    research_plan: list[str]
    rag_results: list[dict[str, Any]]
    web_results: list[dict[str, Any]]
    findings: list[Finding]
    status: Literal[
        "planning",
        "rag_searching",
        "web_searching",
        "synthesizing",
        "complete",
        "failed",
    ]
    error: str | None


# ---------------------------------------------------------------------------
# Structured-output Pydantic models (used with .with_structured_output())
# ---------------------------------------------------------------------------


class ResearchPlan(BaseModel):
    """Output of the planner node — a list of targeted search queries.

    The LLM fills this via ``.with_structured_output(ResearchPlan)``.
    """

    queries: Annotated[
        list[str],
        Field(
            min_length=1,
            max_length=8,
            description=(
                "3 to 8 specific, non-overlapping search queries that together "
                "comprehensively cover the research topic."
            ),
        ),
    ]
    reasoning: Annotated[
        str,
        Field(description="Brief explanation of why these queries cover the topic."),
    ]


class Finding(BaseModel):
    """A single factual finding extracted from search results.

    Used both as the LLM structured-output element and as the final output
    type returned by ``ResearchAgent.run()``.
    """

    text: Annotated[
        str,
        Field(description="Factual claim or insight in 1–3 clear sentences."),
    ]
    source_url: Annotated[
        str,
        Field(description="URL the finding was sourced from."),
    ]
    relevance_score: Annotated[
        float,
        Field(
            ge=0.0,
            le=1.0,
            description="How directly this finding answers the original query (0–1).",
        ),
    ]
    source_type: Annotated[
        Literal["rag", "web"],
        Field(description="Whether the finding came from the vector store or web search."),
    ]
    query_used: Annotated[
        str,
        Field(description="The search query that produced this finding."),
    ]


class FindingList(BaseModel):
    """Wrapper so the synthesizer LLM returns a list of findings."""

    findings: Annotated[
        list[Finding],
        Field(description="All relevant findings extracted from the search results."),
    ]


# ---------------------------------------------------------------------------
# Final agent output
# ---------------------------------------------------------------------------


class ResearchAgentOutput(BaseModel):
    """Structured result returned by ``ResearchAgent.run()``.

    Attributes
    ----------
    findings : list[Finding]
        All extracted findings, sorted by relevance_score descending.
    queries_executed : list[str]
        The search queries that were actually run (from the research plan).
    total_rag_results : int
        Number of chunks retrieved from Qdrant across all queries.
    total_web_results : int
        Number of pages retrieved from Tavily across all queries.
    iteration : int
        Which research loop iteration produced this output.
    """

    findings: list[Finding]
    queries_executed: list[str]
    total_rag_results: int
    total_web_results: int
    iteration: int
